apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: magento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
      - name: magento
        image: registry.datapwn.com/sbovsunovskyi/components-integration-test-magentocms:1.0.0
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: MAGENTO_BASE_URL
          value: http://192.168.99.100:30080
        - name: MAGENTO_BASE_URL_SECURE
          value: https://192.168.99.100:30443
        - name: MAGENTO_USE_SECURE
          value: "0"
        - name: MAGENTO_USE_SECURE_ADMIN
          value: "0"
      imagePullSecrets:
        - name: "reg-datapawn-cred"
---
apiVersion: v1
kind: Service
metadata:
  name: magento
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      name: https
  selector:
    app: magento
